### ISSUE TITLE
Update target to es2017

### ISSUE THREAD

**Issue by hirasso** [swup/webpack-config#3]
Happy new year! 🥳 Maybe it's time to update the `target` for webpack to es2017? That would keep bundle sizes small for async/await. Or even es2020, that would also allow for native optional chaining.

**Comment by daun** [comment]
It's definitely time 🥬 However, switching to microbundle should solve that anyway, no? We'll have to keep this around for any plugins still on webpack, so there's probably no harm in updating it for anyone still using it. If we decide to update it, I'd suggest not hardcoding a support target like 2017 or 2020, but rather sticking with preset-env which should be able to infer the support from a browserslist config.

**Comment by daun** [comment]
On another note, I was trying to move this over to Terser instead of Uglify which compresses a lot better, but there was some compatibility mismatch if I remember correctly. Again, probably not worth the effort considering the upcoming move to microbundle.

**Comment by hirasso** [comment]
It seems like you have the best vision for the upgrade path of swup and its ecosystem. If you want to do all the work, I'll be very thankful :)

**Comment by daun** [comment]
Closing as no longer required 👽
